name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: myskinbuddy-frontend
  ECS_CLUSTER: myskinbuddy-cluster
  ECS_SERVICE: myskinbuddy-frontend-3000
  CONTAINER_NAME: frontend

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::117669335220:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Create .env.production file
        run: |
          cd client
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" > .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "NEXT_PUBLIC_API_URL=http://myskinbuddy-alb-1865825031.us-east-1.elb.amazonaws.com" >> .env.production

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./client
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Force new deployment
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER \
                                --service $ECS_SERVICE \
                                --force-new-deployment \
                                --region $AWS_REGION
